# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jawgrind
email: trey@jawgrind.com
description: A podcast discussing every episode of Star Trek.
url: "http://jawgrind.com" # the base hostname & protocol for your site
twitter_username: jawgrind
defaults:
  -
    values:
      layout: "episode"

# Build settings
markdown: kramdown
